### ISSUE TITLE
Exception while unloading a virtual sensor using local or remote wrappers

### ISSUE THREAD

**Issue by sarni** [LSIR/gsn#13]
I find now that when stopping GSN (ant stop), there is an error if any
virtual sensor using local wrapper or either of the remote wrappers.

I can load memoryDataVS.xml and freeDiskSpace-NeedsJDK6.xml and the stop
script executes without error.

However if any of:
* diskSpacePlotVS-NeedsJDK6.xml (wrapper="remote-rest">),
* memoryPlotVS.xml (wrapper="local">),
* remote_rest_test.xml (wrapper="remote-rest">) or
* remote_push_test.xml (wrapper="remote">)
Are loaded when the stop script is executed, then errors are generated.
There is some difference in the errors as can be seen in the attached log
file which was recorded while I started and stopped GSN with different VS's
loaded.

I guess that errors when stopping are not critical but they may be
symptomatic of something more serious.
> Imported from here: https://sourceforge.net/apps/trac/gsn/ticket/44
> Files are on SourceForge Issue tracker: https://sourceforge.net/apps/trac/gsn/ticket/44

**Comment by ebiiii** [comment]
Should be solved with v2.0.0
