### ISSUE TITLE
implement a CoAP wrapper

### ISSUE THREAD

**Issue by ebiiii** [LSIR/gsn#58]
can use this java library: https://github.com/okleine/nCoAP for example

**Comment by m6461** [comment]
Hey, have you already implemented it? If not, may I try? I am new here, so sorry if the question is naive.

**Comment by ebiiii** [comment]
Hello, no we didn't started yet with this one. So feel free to give it a try. You can find some documentation on how to implement wrappers here: https://github.com/LSIR/gsn/wiki/how-to-write-a-new-wrapper . Let me know if you have questions.

**Comment by m6461** [comment]
thanks. will get back to you if i face some problems.

**Comment by iseitani** [comment]
@m6461  if you need I have the wrapper and virtual sensor for CoAP using Californium

**Comment by m6461** [comment]
@iseitani that would be a great help. thanks a lot in advance. you can send in md.anowarul.abedin@ltu.se, or just let me know how I should collect.

**Comment by iseitani** [comment]
You will need californium-core & element-connector libraries(you can find them on mvnrepository).
I had a few system crashes and didn't commit my code, I hope I will do this the following weeks.

[GSN-COAP.zip](https://github.com/LSIR/gsn/files/119202/GSN-COAP.zip)

**Comment by m6461** [comment]
nice! if necessary, i will modify it and will try to improve. will keep you updated about it.

**Comment by ebiiii** [comment]
Thanks @iseitani, the CoAP wrapper has been added to the defaults wrappers : 339dafe2c810e47fb762cb09a593fd6f8dfa12e4

Feel free to re-open the issue if you have any trouble using it.
