### ISSUE TITLE
deploying new sensor

### ISSUE THREAD

**Issue by mvishnuprathap** [LSIR/gsn#67]
how can I deploy a new virtual sensor into gsn ? How can I get the values ? Can someone please post the commands required for this ?

**Comment by ebiiii** [comment]
Once you have a running instance (https://github.com/LSIR/gsn/wiki/Getting-started), you deploy new virtual sensors by adding xml configuration files into the virtual-sensors folder. The configuration file will tell GSN how to get the input data, through a wrapper and its parameters, and what to do with the data (the simplest one being the BridgeVirtualSensor which does no processing). The configuration file also contains a description of the data types of the received values. You can find examples of such configuration files in the folder virtual-sensors/examples. The values can be visualized through the web interface (at localhost:22001/) or you can query the API (https://github.com/LSIR/gsn/wiki/GSN-REST-Interface). 
You can find more details in the wiki : https://github.com/LSIR/gsn/wiki/Documentation
