### ISSUE TITLE
Time Unit in GSN

### ISSUE THREAD

**Issue by mvishnuprathap** [LSIR/gsn#74]
What is the unit of time measured by sensors in GSN ? I get something like this ?
![screenshot from 2016-03-27 16 30 24](https://cloud.githubusercontent.com/assets/4988410/14065100/854afa20-f439-11e5-9f76-97c6867bb640.png)

**Comment by ebiiii** [comment]
It is the Unix time (https://en.wikipedia.org/wiki/Unix_time) in milliseconds. Or simply the number of milliseconds from January 1st, 1970.

**Comment by mvishnuprathap** [comment]
Thank you Mr. Ebiiii. Your information has been a great help. :-)
