### ISSUE TITLE
Database Modification

### ISSUE THREAD

**Issue by mvishnuprathap** [LSIR/gsn#75]
Is it possible to modify database and then deploy sensors ? I got several errors occured when I tried to modify database and run the sensors again, even when I had default value of the sensors initialized to NULL.
![problem](https://cloud.githubusercontent.com/assets/4988410/14137958/1e3291da-f688-11e5-92e8-4475927c544d.png)

**Comment by ebiiii** [comment]
Normally you shouldn't modify the database (or maybe if you want to add an index) tables that are managed by GSN. GSN supposes that the columns correspond to the field of the virtual sensor and populate them accordingly. If you add columns and provide them a default value (ALTER TABLE vsensorname ALTER latitude SET DEFAULT '46.602'), it should work however...
