### ISSUE TITLE
Reliability of Values

### ISSUE THREAD

**Issue by mvishnuprathap** [LSIR/gsn#76]
Can we measure reliability of temperature values given by a sensor in GSN ?  What is the possible way ?

**Comment by ebiiii** [comment]
If you define reliability as the deviation of the measured values from a ground truth, then you can for example have a second virtual sensor that is providing you the ground truth and you can write you own processing class which merge both and compute the difference.

If you measure the reliability by identifying when the sensor fails (for example reporting impossible values) then you can again write your own processing class and detect those failure and maybe add an extra field to the virtualsensor to reflect the frequency of failures.

If you have several sensors distributed geographically and want to detect if one is reporting consistent values compared to the other or according to a model, it start to be a little bit more complex, but you can still merge all virtual sensors into a single one that will be maintaining a model and computing the likelihood of the incoming data. 

There are probably also other ways, depending on what you call reliability...
