### ISSUE TITLE
How to enable debuging in GSN server ?

### ISSUE THREAD

**Issue by milangroshev** [LSIR/gsn#77]
I installed the GSN server using the gsn_1.1.8_all.deb file. In the /var/log/gsn.log i get some informations about how the server works but no DEBUG. Is there any way to enable debuging ?

Tnx a lot in advanced

**Comment by ebiiii** [comment]
The logs are by default only logging errors. If you want to add some more verbose debug output, you can edit the logger configuration file at /opt/gsn/1.1.8/conf/log4j2.xml 

If you have also the source-code and want to use for example the step-by-step debugger of eclipse, you will have to edit the init script /etc/init.d/gsn to add something like that to the command line : 

-Xdebug -agentlib:jdwp=transport=dt_socket,address=10001,server=y,suspend=n

But in this case it is easier to just run GSN inside eclipse ;-)
