### ISSUE TITLE
Input Stream Error

### ISSUE THREAD

**Issue by mvishnuprathap** [LSIR/gsn#80]
The os version i'm using is ubuntu 14.04 LTS, 64 bit OS. The error occured when I tried to simulate the sensor named with the xml file " sensorscope2sample.xml ". I'm attaching the log of the error occured when I simulated
[gsn_sensorscopesample2_error.txt](https://github.com/LSIR/gsn/files/689040/gsn_sensorscopesample2_error.txt)

**Comment by ebiiii** [comment]
The sensorscope wrapper that is used in this virtual sensor example file tries to connect to a server that doesn't exist anymore. If you need to retrieve data from a sensorscope station, please edit the xml file and specify the right url for it. If it is just for testing, you may want to try another virtual sensor as I'm not aware of any publicly available sensorscope station that you could connect to.

Most of the sample xml files in the virtual sensor folder need some manual adjustments to be used, but their content should be self explicit. If not, feel free to open another issue.
