### ISSUE TITLE
database table

### ISSUE THREAD

**Issue by mvishnuprathap** [LSIR/gsn#82]
I get so many table with numbers as names when simulating virtual sensors in GSN middleware. Is there any way to overcome this ? I just want the tables of sensors. Is there a way out ?

**Comment by ebiiii** [comment]
Those are the temporary tables used for the wrappers input before they get into the processing class of the virtual sensor. Normally they should be cleaned up when stopping GSN. To avoid having them persisted in the same database as the virtual sensors' output, you can add this to your gsn.xml configuration file:

```xml
<sliding>
      <storage user="sa" password="" driver="org.h2.Driver" url="jdbc:h2:mem:sliding;DB_CLOSE_DELAY=-1" />
</sliding>
```
